logging:
  level:
    error

application:
  profiles:
    active: "dev"
  main:
    banner-mode: "off"

server:
  email: default@mkyong.com

---
application:
  profiles: dev
  resource:
    config:
     location : classpath:pojo/
     enable : true
  model:
   config: 
     location : classpath:/pojo/models
     packages : org.brijframework.dao
     enable : true
  bean:
   config: 
     location : classpath:/pojo/beans
     packages : org.brijframework.dao
     enable : true
server:
  email: dev@mkyong.com
  cluster:
    - ip: 127.0.0.1
      path: /dev1
    - ip: 127.0.0.2
      path: /dev2
    - ip: 127.0.0.3
      path: /dev3

---
application:
  profiles: prod
server:
  email: prod@mkyong.com
  cluster:
    - ip: 192.168.0.1
      path: /app1
    - ip: 192.168.0.2
      path: /app2
    - ip: 192.168.0.3
      path: /app3