# application
---
application:
   name: Test User
   bootstrap: 
       config:
          model:
             data:
                json :
                  enable : true
                  location : \\model_data
             meta:
                json :
                  location : \\model_meta
          jdbc:
               build : 
                 json : 
                  -
                     enable : true
                     location : \\jdbc\\jdbc_build
                     catalog : fadsan_school_ui
                     source : DEV_DATA_SOURCE_UI
                     role: update
                  -
                     enable : true
                     location : \\jdbc\\jdbc_build
                     catalog : fadsan_school_ui
                     source : DEV_DATA_SOURCE_UI
                     role: update
